### PR TITLE
format: resolve variables in customFormatter field

### LINKED ISSUE #2582: `customFormatter` setting in `go.alternateTools` does not resolve variables in path
### What version of Go, VS Code & VS Code Go extension are you using?
<details><summary>Version Information</summary><br>

* Run `go version` to get version of Go from _the VS Code integrated terminal_.
```
go version go1.19.4 darwin/arm64
```

* Run `gopls -v version` to get version of Gopls from _the VS Code integrated terminal_.
```
gopls -v version
Build info
----------
golang.org/x/tools/gopls v0.11.0
    golang.org/x/tools/gopls@v0.11.0 h1:/nvKHdTtePQmrv9XN3gIUN9MOdUrKzO/dcqgbG6x8EY=
    github.com/BurntSushi/toml@v1.2.1 h1:9F2/+DoOYIOksmaJFPw1tGFy1eDnIJXg+UHjuD8lTak=
    github.com/google/go-cmp@v0.5.9 h1:O2Tfq5qg4qc4AmwVlvv0oLiVAGB7enBSJ2x2DqQFi38=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/exp@v0.0.0-20221031165847-c99f073a8326 h1:QfTh0HpN6hlw6D3vu8DAwC8pBIwikq0AI1evdm+FksE=
    golang.org/x/exp/typeparams@v0.0.0-20221031165847-c99f073a8326 h1:fl8k2zg28yA23264d82M4dp+YlJ3ngDcpuB1bewkQi4=
    golang.org/x/mod@v0.7.0 h1:LapD9S96VoQRhi/GrNTqeBJFrUjs5UHCAtTlgwA5oZA=
    golang.org/x/sync@v0.1.0 h1:wsuoTGHzEhffawBOhz5CYhcrV4IdKZbEyZjBMuTp12o=
    golang.org/x/sys@v0.2.0 h1:ljd4t30dBnAvMZaQCevtY0xLLD0A+bRZXbgLMLU1F/A=
    golang.org/x/text@v0.4.0 h1:BrVqGRd7+k1DiOgtnFvAkoQEWQvBc25ouMJM6429SFg=
    golang.org/x/tools@v0.3.1-0.20221213193459-ca17b2c27ca8 h1:7/HkGkN/2ktghBCSRRgp31wAww4syfsW52tj7yirjWk=
    golang.org/x/vuln@v0.0.0-20221109205719-3af8368ee4fe h1:qptQiQwEpETwDiz85LKtChqif9xhVkAm8Nhxs0xnTww=
    honnef.co/go/tools@v0.3.3 h1:oDx7VAwstgpYpb3wv0oxiZlxY+foCpRAwY7Vk6XpAgA=
    mvdan.cc/gofumpt@v0.4.0 h1:JVf4NN1mIpHogBj7ABpgOyZc65/UUOkKQFkoURsz4MM=
    mvdan.cc/xurls/v2@v2.4.0 h1:tzxjVAj+wSBmDcF6zBB7/myTy3gX9xvi8Tyr28AuQgc=
go: go1.19.4
```
* Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders.
```
code -v
1.74.0
5235c6bb189b60b01b1f49062f4ffa42384f8c91
arm64
```
* Check your installed extensions to get the version of the VS Code Go extension
```
0.37.0
```
* Run Ctrl+Shift+P (Cmd+Shift+P on Mac OS) > `Go: Locate Configured Go Tools` command.
```
Checking configured tools....
GOBIN: undefined
toolsGopath: 
gopath: /Users/dcarney/go
GOROOT: /opt/homebrew/Cellar/go/1.19.4/libexec
PATH:  (redacted)

	go:	/opt/homebrew/Cellar/go/1.19.4/libexec/bin/go: go version go1.19.4 darwin/arm64

	gotests:	not installed
	gomodifytags:	not installed
	impl:	not installed
	goplay:	not installed
	dlv:	/Users/dcarney/go/bin/dlv	(version: v1.9.1 built with go: go1.19.2)
	staticcheck:	/Users/dcarney/go/bin/staticcheck	(version: v0.3.3 built with go: go1.19.2)
	gopls:	/Users/dcarney/go/bin/gopls	(version: v0.11.0 built with go: go1.19.4)

go env
Workspace Folder (redacted): (redacted)
	GO111MODULE="on"
	GOARCH="arm64"
	GOBIN=""
	GOCACHE="/Users/dcarney/Library/Caches/go-build"
	GOENV="/Users/dcarney/Library/Application Support/go/env"
	GOEXE=""
	GOEXPERIMENT=""
	GOFLAGS=""
	GOHOSTARCH="arm64"
	GOHOSTOS="darwin"
	GOINSECURE=""
	GOMODCACHE="/Users/dcarney/go/pkg/mod"
	GOOS="darwin"
	GOPATH="/Users/dcarney/go"
	GOPROXY="https://proxy.golang.org,direct"
	GOROOT="/opt/homebrew/Cellar/go/1.19.4/libexec"
	GOSUMDB="sum.golang.org"
	GOTMPDIR=""
	GOTOOLDIR="/opt/homebrew/Cellar/go/1.19.4/libexec/pkg/tool/darwin_arm64"
	GOVCS=""
	GOVERSION="go1.19.4"
	GCCGO="gccgo"
	AR="ar"
	CC="clang"
	CXX="clang++"
	CGO_ENABLED="0"
	GOMOD="(redacted)"
	GOWORK=""
	CGO_CFLAGS="-g -O2"
	CGO_CPPFLAGS=""
	CGO_CXXFLAGS="-g -O2"
	CGO_FFLAGS="-g -O2"
	CGO_LDFLAGS="-g -O2"
	PKG_CONFIG="pkg-config"
	GOGCCFLAGS="-fPIC -arch arm64 -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lt/r0k33__90291gp354_ydjs5w0000gn/T/go-build2975243760=/tmp/go-build -gno-record-gcc-switches -fno-common"
	

```
</details>

### Share the Go related settings you have added/edited

Run `Preferences: Open Settings (JSON)` command to open your settings.json file.
Share all the settings with the `go.` or `["go"]` or `gopls` prefixes.

```
  "go.enableCodeLens": {
    "references": false,
    "runtest": false
  },
  "gopls": {
    "build.directoryFilters": [
      // Bazel symlinks
      "-bazel-bin",
      "-bazel-gocode",
      "-bazel-out",
      "-bazel-testlogs"
    ],
    "ui.semanticTokens": true,
    "ui.codelenses": {
      "gc_details": false,
      "regenerate_cgo": false,
      "generate": false,
      "test": false,
      "tidy": false,
      "upgrade_dependency": false,
      "vendor": false
    },
    "build.memoryMode": "DegradeClosed"
  },
  "go.useLanguageServer": true,
  "go.buildOnSave": "off",
  "go.lintOnSave": "off",
  "go.vetOnSave": "off",
  "go.toolsEnvVars": {
    "CGO_ENABLED": "0"
  },
  "go.languageServerFlags": [
        "-rpc.trace"
  ],
  "go.formatTool": "custom",
  "go.alternateTools": {
      "customFormatter": "${workspaceFolder}/bin/goimports.sh"
      "gopls": "${workspaceFolder}/bin/gopls.sh"
  }
}
```

I recently noticed [this commit](https://github.com/golang/vscode-go/commit/8f81613ec4bafd5358a3ccd45c08f91356b71ca3#diff-935221ada83158ef414a0ac012a526fef08974f14bf8738ad770ab5570fb5f16R147), which enables the use of a custom formatter while also using `gopls`! 🎉 

However, it appears that the value supplied for the path to the custom formatter doesn't get variables resolved, 

For example, given the following in `.vscode/settings.json`:
```
 "go.formatTool": "custom",
 "go.alternateTools": {
      "gopls": "${workspaceFolder}/bin/gopls.sh",
      "customFormatter": "${workspaceFolder}/bin/goimports.sh"
  }
```

the alternate tool for `gopls` gets resolved properly, but the tool for `customFormatter` does not, leading to a popup like:

vscode-go

(actual PATH redacted)

### Steps to reproduce the behavior:
- set "go.formatTool" to "custom"
- set "customFormatter" to a valid path that contains the `${workspaceFolder}` variable in "go.alternateTools"
- save a change to a `.go` file to attempt to run the custom formatter

### Screenshots or recordings
See above screencap of the popup that is shown when such a customFormatter value is used.

### PR DESCRIPTION
**Pull request by uniquefine**
Fixes #2582

### CODE REVIEW

**Comment by dcarney-stripe** [comment]
@uniquefine Are you still planning to get this PR merged?  I would love to see this long-standing issue get closed, as I have some code that would be able to take advantage of the fix.

**Comment by uniquefine** [comment]
Yes, I was waiting for a review. I'll resolve the conflicts and ping the maintainers in slack.

**Comment by Olshansk** [comment]
🚀

**Comment by telnet2** [comment]
I encountered the same issue. In my case, I want to add `-local xxx` argument to `goimports`, which seems not doable using `go.formatTool=goimports`. I created a `goimports.sh` within the workspace and tried to call it, but it failed with "not found" error message.

**Comment by dcarney-stripe** [comment]
@uniquefine What's left to get this merged?  I'd still really like to see it get merged in.

**Pull request closed without merging**
