### PR TITLE
Dev.go2go

### PR DESCRIPTION
**Pull request by oma-code**
This PR will be imported into Gerrit with the title and first
comment (this text) used to generate the subject and body of
the Gerrit change.

**Please ensure you adhere to every item in this list.**

More info can be found at https://github.com/golang/go/wiki/CommitMessage

+ The PR title is formatted as follows: `frob the quux before blarfing`
  + The part after the colon uses the verb tense + phrase that completes the blank in,
    "This change modifies Go to ___________"
  + Lowercase verb after the colon
  + No trailing period
  + Keep the title as short as possible. ideally under 76 characters or shorter
+ No Markdown
+ The first PR comment (this one) is wrapped at 76 characters, unless it's
  really needed (ASCII art, table, or long link)
+ If there is a corresponding issue, add either `Fixes golang/vscode-go#1234` or `Updates golang/vscode-go#1234`
  (the latter if this is not a complete fix) to this comment
+ If referring to a repo, you can use the `owner/repo#issue_number` syntax:
  `Fixes golang/tools#1234`
+ We do not use Signed-off-by lines in Go. Please don't add them.
  Our Gerrit server & GitHub bots enforce CLA compliance instead.
+ Delete these instructions once you have read and applied them
``

### CODE REVIEW

**Comment by hyangah** [comment]
Thanks for the PR. I don't think this dev.go2go branch modification is no longer necessary given that most of the recent dev works related to generics are done in the official `dev.typeparams` branch. Please find the instruction on how to set up go tools and gopls.

https://github.com/golang/tools/blob/master/gopls/doc/advanced.md#working-with-generic-code

cc @stamblerre @findleyr

**Comment by dzpt** [comment]
@hyangah  i got the error installing 

```
GO111MODULE=on gotip get -tags=typeparams golang.org/x/tools/gopls@master golang.org/x/tools@master
go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
# golang.org/x/tools/internal/typeparams
../pkg/mod/golang.org/x/tools@v0.1.6-0.20210723180839-46d1522a5d83/internal/typeparams/typeparams.go:25:23: undefined: ast.ListExpr
../pkg/mod/golang.org/x/tools@v0.1.6-0.20210723180839-46d1522a5d83/internal/typeparams/typeparams.go:37:15: undefined: ast.ListExpr
../pkg/mod/golang.org/x/tools@v0.1.6-0.20210723180839-46d1522a5d83/internal/typeparams/typeparams.go:57:20: cannot use (*types.Signature).TParams(sig) (type *types.TypeParams) as type []*types.TypeName in return argument
../pkg/mod/golang.org/x/tools@v0.1.6-0.20210723180839-46d1522a5d83/internal/typeparams/typeparams.go:62:14: iface.HasTypeList undefined (type *types.Interface has no field or method HasTypeList)
../pkg/mod/golang.org/x/tools@v0.1.6-0.20210723180839-46d1522a5d83/internal/typeparams/typeparams.go:79:22: cannot use (*types.Named).TParams(named) (type *types.TypeParams) as type []*types.TypeName in return argument
```

**Comment by findleyr** [comment]
@dzpt this is on me: I need to update x/tools to use the new APIs.

For now, can you try omitting the `-tags=typeparams` from your `gotip get` invocation?

**Comment by dzpt** [comment]
@findleyr thank you, it works now but i still see the warning from `go-staticcheck`

`expected '(', found '[' (compile)go-staticcheck` ?

**Comment by dzpt** [comment]
@findleyr Then if i enable go module , it won't work anymore?

**Comment by findleyr** [comment]
@dzpt I'm assuming go-staticcheck needs to be rebuilt as well, but also has probably not been updated to check generic code.

**Pull request closed without merging**
