### PR TITLE
webpack: bundle the extension

### LINKED ISSUE #53: performance: consider bundling extension
Original bug report is https://github.com/microsoft/vscode-go/issues/2997

This extension got bigger. vsce recommends https://aka.ms/vscode-bundle-extension

```
This extension consists of 2266 files, out of which 1509 are JavaScript files. 
For performance reasons, you should bundle your extension: 
https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary 
files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
```

https://github.com/microsoft/vscode-extension-telemetry/issues/41 
(due to https://github.com/microsoft/ApplicationInsights-node.js-native-metrics/issues/4) was one of the road blockers. We can probably prune the dependency. 

Not sure about interaction with debug adapter yet.

### PR DESCRIPTION
**Pull request by OneOfOne**
This PR allows the extension to be bundled.

Fixes golang/vscode-go#53

### CODE REVIEW

**Comment by OneOfOne** [comment]
@hyangah did you get a chance to check the updates? after all those years, gerrit still confuses the crap out of me.

**Comment by eliben** [comment]
It seems like this commit is related to my being unable to launch the extension now in a Extension Development Host, it complains about being unable to find "dist/goMain.js"

**Comment by eliben** [comment]
@hyangah

**Comment by hyangah** [comment]
https://go-review.googlesource.com/c/vscode-go/+/241861

And, in the mean time, run `npm run test-compile`. Sorry for the inconvenience.

**Pull request closed without merging**
