### PR TITLE
src/goCheck.ts: relax generated code detection rule

### PR DESCRIPTION
**Pull request by butuzov**
Implements set of changes that enhance user experience with generated go files.

1) It allows checking other (then) the first line of the file for target msg.
2) It uses a lookup table to cache results of previous checks
3) it changes regexp pattern
   from
   `/^// Code generated .* DO NOT EDIT.$

   to
   `^// .*DO NOT EDIT.?`

  Aiming to show generated message to files also available in go codebase, 
  that does not follow the standard "generated" pattern.

  Fixes golang/vscode-go#68

### CODE REVIEW

**Comment by hyangah** [comment]
@butuzov I left comments in gerrit (https://golang.org/cl/234359), the default review tool in the Go project. Can you take a look? 

Sorry for this confusing PR review process. I hope we can get it sorted out soon. Thanks!!

**Comment by butuzov** [comment]
duplicating my answer here as i have no idea why "replay" is in draft state (should i checkbox `resolved` for that?).

> Switching to `workspaceState` will do the trick, in addition, we can flush state every week or so, to keep its footprint reasonably small. Is it "OK" solution, what do you think?

**Comment by butuzov** [comment]
all my comments appear as "draft", any tutorial on how Gerrit works?

**Comment by hyangah** [comment]
As we discussed offline, let's close this - since now gopls is enabled by default and it handles the problem better.
We really appreciate your effort to make the default experience better! Thanks!

**Pull request closed without merging**
